In [2]:
import pandas as pd
import numpy as np
df = pd.read_csv(r"C:\Users\danie\OneDrive\Documentos\Cursos\python_ds_linkedin\base_datos_2008.csv")

La correlación no nos funciona para encontrar explicaciónes pero sí nos funciona para identificar cuando dos variables están correlacionadas.
Los valores entre -0,3 y 0,3 son consideradas muy leves.
Los valores a partir de 0,6 y 0,7 en cualquier de los dos signos nos demuestran una correlazión fuerte (positiva o negativa)

CORRELACIONES UTILIZANDO NUMPY

In [8]:
np.corrcoef(df["ArrDelay"], df["DepDelay"])

array([[nan, nan],
       [nan, nan]])

In [10]:
#Debemos borrar las celdas vacías
df.dropna(inplace = True, subset=["ArrDelay","DepDelay"])

In [11]:
np.corrcoef(df["ArrDelay"], df["DepDelay"])

array([[1.        , 0.93139078],
       [0.93139078, 1.        ]])

La correlación de una columna con ella misma siempre es 1.
Estas matrices siempre serán simétricas.

In [13]:
#Agregando más variable a el estudio de correlaciónes
np.corrcoef([df["ArrDelay"], df["DepDelay"], df["DepTime"]])

array([[1.        , 0.93139078, 0.17827465],
       [0.93139078, 1.        , 0.20198125],
       [0.17827465, 0.20198125, 1.        ]])

CORRELACIONES UTILIZANDO PANDAS

In [16]:
#Primero debemos borrar aquellas columnas que contienen valores constantes o valores de texto
df.drop(inplace = True, columns=["Year","Cancelled", "Diverted"])

In [17]:
df.corr()

Month  DayofMonth  DayOfWeek   DepTime  CRSDepTime  \
Month              1.000000   -0.000402  -0.005350 -0.010321   -0.008426   
DayofMonth        -0.000402    1.000000   0.004762 -0.001555   -0.001745   
DayOfWeek         -0.005350    0.004762   1.000000  0.005660    0.005666   
DepTime           -0.010321   -0.001555   0.005660  1.000000    0.968550   
CRSDepTime        -0.008426   -0.001745   0.005666  0.968550    1.000000   
ArrTime           -0.000377   -0.001505   0.003376  0.713081    0.697293   
CRSArrTime         0.000353   -0.001744   0.005569  0.791431    0.790820   
FlightNum          0.005307   -0.000283  -0.001439 -0.006075   -0.012513   
ActualElapsedTime -0.014061    0.000598   0.012929 -0.017070   -0.017184   
CRSElapsedTime    -0.006345    0.001384   0.015013 -0.013684   -0.011774   
AirTime           -0.012413    0.000950   0.013915 -0.023170   -0.021086   
ArrDelay          -0.042058    0.001607   0.010558  0.178275    0.116894   
DepDelay          -0.030498    0.003299   0.015425  0.201981    0.138850   
Distance          -0.005558    0.001363   0.016730 -0.016523   -0.012189   
TaxiIn             0.006904   -0.002933   0.010244 -0.042255   -0.047563   
TaxiOut           -0.016249   -0.000674  -0.007207  0.050649    0.039827   
CarrierDelay      -0.000232    0.000249   0.012319  0.001787   -0.053916   
WeatherDelay       0.005598    0.001249   0.006441  0.023042    0.006909   
NASDelay           0.013533    0.004114  -0.007274 -0.013341   -0.052253   
SecurityDelay     -0.003165   -0.000276   0.004513 -0.009065   -0.011447   
LateAircraftDelay  0.002176    0.009385   0.012024  0.205079    0.191594   

                    ArrTime  CRSArrTime  FlightNum  ActualElapsedTime  \
Month             -0.000377    0.000353   0.005307          -0.014061   
DayofMonth        -0.001505   -0.001744  -0.000283           0.000598   
DayOfWeek          0.003376    0.005569  -0.001439           0.012929   
DepTime            0.713081    0.791431  -0.006075          -0.017070   
CRSDepTime         0.697293    0.790820  -0.012513          -0.017184   
ArrTime            1.000000    0.862455  -0.017674           0.037625   
CRSArrTime         0.862455    1.000000  -0.029613           0.051469   
FlightNum         -0.017674   -0.029613   1.000000          -0.319347   
ActualElapsedTime  0.037625    0.051469  -0.319347           1.000000   
CRSElapsedTime     0.038654    0.056583  -0.326568           0.979875   
AirTime            0.030320    0.044016  -0.334444           0.984241   
ArrDelay           0.066021    0.113087   0.016603           0.093925   
DepDelay           0.073540    0.132823   0.009834           0.044380   
Distance           0.029023    0.046196  -0.348495           0.964521   
TaxiIn             0.007132   -0.006540  -0.009481           0.158444   
TaxiOut            0.049583    0.059792   0.016576           0.267801   
CarrierDelay      -0.058128   -0.053370   0.057192          -0.032919   
WeatherDelay      -0.020296    0.007568   0.064391          -0.013712   
NASDelay           0.019385   -0.010596   0.004423           0.203805   
SecurityDelay     -0.005345   -0.009237  -0.001206           0.000318   
LateAircraftDelay -0.009715    0.153406  -0.034556          -0.087003   

                   CRSElapsedTime  ...  ArrDelay  DepDelay  Distance  \
Month                   -0.006345  ... -0.042058 -0.030498 -0.005558   
DayofMonth               0.001384  ...  0.001607  0.003299  0.001363   
DayOfWeek                0.015013  ...  0.010558  0.015425  0.016730   
DepTime                 -0.013684  ...  0.178275  0.201981 -0.016523   
CRSDepTime              -0.011774  ...  0.116894  0.138850 -0.012189   
ArrTime                  0.038654  ...  0.066021  0.073540  0.029023   
CRSArrTime               0.056583  ...  0.113087  0.132823  0.046196   
FlightNum               -0.326568  ...  0.016603  0.009834 -0.348495   
ActualElapsedTime        0.979875  ...  0.093925  0.044380  0.964521   
CRSElapsedTime        

In [18]:
#Para visualizar gráficamente la matriz de correlaciones
#Primero redondeamos la matríz para que no tenga tantos decimales
corr = round(df.corr(),3)
#Generamos la matríz
corr.style.background_gradient()
#El degradado es según la intensidad de la correlación

Matplotlib is building the font cache; this may take a moment.


TEST DEL CHI CUADRADO
Es una prueba solida para determinar la relación entre dos variables cualitativas utilizando tablas de contingencias
Compara la suma de diferencias al cuadrado, entre lo que estamos esperando.
Una de las debilidades de este test, es que no permite cuantificar cada una de las relaciones entre las variables. Pero sí permite afirmaciones globales como "Fumar esta significativamente relacionado con el cáncer de pulmón".


In [3]:
np.random.seed(0) #Esto funciona para obtener los mismos valores que la clase cuando aplique funciones aleatorias
df = df[df["Origin"].isin(["HOU","ATL","IND"])] #Subset con aquellos casos que tengan un origen con los que tenemos
df = df.sample(frac=1) # reordenar la base de datos
df = df[0:10000] #Sólo seleccionamos 10k filas porque entre más grande es el dataset siempre encontraremos una relación aunque sea pequeña entre las variablaes. Y eso no nos interesa

In [4]:
df["BigDelay"] = df["ArrDelay"] > 30 #df["BigDelay"] será igual a True cuando se cumpla que df["ArrDelay"]>30 y False en el caso contrario
observados = pd.crosstab(index = df["BigDelay"], columns = df["Origin"], margins= True) #Creamos una tabla de contingencia

In [5]:
observados

Origin     ATL   HOU  IND    All
BigDelay                        
False     6927   883  765   8575
True      1197   129   99   1425
All       8124  1012  864  10000

In [6]:
from scipy.stats import chi2_contingency #Paquete para realizar el test

In [7]:
test = chi2_contingency(observados)
test

(8.939538453043031,
 0.17700704816414425,
 6,
 array([[ 6966.33,   867.79,   740.88,  8575.  ],
        [ 1157.67,   144.21,   123.12,  1425.  ],
        [ 8124.  ,  1012.  ,   864.  , 10000.  ]]))

Del resultado anterior: 
El primer valor es el estadístico: La suma de las diferencias al cuadrado
El segundo es el valor "p"
Y finalmente la tabla de valores esperados que es lo que compararemos con la tabla de valores observados, lo cuál hará la función automáticamente

In [8]:
esperados = pd.DataFrame(test[3]) #Crear un dataframe de los valores obtenidos en el test para visualizarla de una manera más cómoda
esperados #Valores teóricos esperados si no hubiese ningún tipo de relación

0        1       2        3
0  6966.33   867.79  740.88   8575.0
1  1157.67   144.21  123.12   1425.0
2  8124.00  1012.00  864.00  10000.0

In [9]:
esperados_rel = round(esperados.apply(lambda r: r/len(df)*100, axis=1),2)
observados_rel= round(observados.apply(lambda r: r/len(df)*100, axis=1),2)

In [11]:
observados_rel


Origin      ATL    HOU   IND     All
BigDelay                            
False     69.27   8.83  7.65   85.75
True      11.97   1.29  0.99   14.25
All       81.24  10.12  8.64  100.00

In [12]:
esperados_rel

0      1     2       3
0  69.66   8.68  7.41   85.75
1  11.58   1.44  1.23   14.25
2  81.24  10.12  8.64  100.00

In [13]:
test[1]

0.17700704816414425

Si el p-valor< 0.05, hay diferencias significativas: Hay relación entre variables.
Si el p-valor> 0.05, no hay diferencias significativas: No hay relaciones entre variables.