In [1]:
import numpy as np

In [4]:
valoraciones = np.array([[5, 4, 6, 7],[8, 9, 12, 14],[15, 20, 21, 23],[2, 3, 9, 20]])
valoraciones

array([[ 5,  4,  6,  7],
       [ 8,  9, 12, 14],
       [15, 20, 21, 23],
       [ 2,  3,  9, 20]])

In [5]:
valoraciones[0][2]

6

In [6]:
valoraciones[0, 2]

6

In [7]:
valoraciones2= np.array([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9],[10, 11, 12]]])
valoraciones2

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [8]:
valoraciones2[1,1, 0]

10

In [9]:
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [10]:
#Sumar uno a cada elemnto de una matriz
valoraciones2 + np.ones((2, 2, 3))

array([[[ 2.,  3.,  4.],
        [ 5.,  6.,  7.]],

       [[ 8.,  9., 10.],
        [11., 12., 13.]]])

In [11]:
np.mean(valoraciones2)

6.5

In [14]:
#Calcular la media en un solo eje
np.mean(valoraciones2, axis = 2)

array([[ 2.,  5.],
       [ 8., 11.]])